### PR TITLE
feat: add additional color customization

### PR DESCRIPTION
**Pull request by drewxs**
This PR adds additional color customization options which include the foreground, background, and the greys.
The defaults are used if they're not set.

List of added settings:
- tmux_power_fg
- tmux_power_bg
- tmux_power_g01
- tmux_power_g02
- tmux_power_g03
- tmux_power_g04
- tmux_power_g05
- tmux_power_g06
- tmux_power_g07
- tmux_power_g08
- tmux_power_g00
- tmux_power_g10
- tmux_power_g11
- tmux_power_g12

### CODE REVIEW

**Comment by jalcine** [comment]
This would be a welcome addition for me as I use @tinted-theming/base16-tmux and using its ideas of colors would be a great improvement.

(Originally published at: https://jacky.wtf/2023/1/rcqA)

**Comment by drewxs** [comment]
Would resolve #46

**Comment by wadegbow** [comment]
this has been working great for me

**Comment by tesarlukas** [comment]
I need this so much. Been using it for over a year and an option to further change colors would be amazing.

**Comment by wfxr** [comment]
@drewxs Thank you for your contribution to the project! I'm really sorry that I haven't maintained this project for a long time, this great PR was accidentally closed.

**Comment by wfxr** [comment]
@drewxs FYI, I have cleaned up the unused colors in 9f7701bc06b3ec2748bb07fbdd95f6ce3d4757e3. Now we only keep the following 5:

```
set -g @tmux_power_g0 "#262626"
set -g @tmux_power_g1 "#303030"
set -g @tmux_power_g2 "#3a3a3a"
set -g @tmux_power_g3 "#444444"
set -g @tmux_power_g4 "#626262"
```

**Pull request merged**
